### ISSUE TITLE
Observability support for kArmor

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/kubearmor-client#53]
- [x] support different build options (kubearmor, cilium, discovery)
	- [ ] show build options in the `karmor version`
- [x] Handle karmor observe #54 
	- [x] Support different filters
- [x] Handle `karmor policy discovery` (with filters)
	- #56 
	- #57

**Comment by wazir-ahmed** [comment]
@Ankurk99 @nyrahul Since we're bringing the functionalities we had in the APD's shell scripts to `karmor`, we also need a command which does the job of [dbclear.sh](https://github.com/accuknox/discovery-engine/blob/5df1489d264bbce5455082ac1f972ea807a175d2/scripts/dbclear.sh).

(OR) we could bring a ENV flag (or configuration field) in APD which make the APD clear the DB during startup and start doing the discovery after that.

**Comment by Ankurk99** [comment]
I think adding a command will make more sense as user could themself want to run dbclear even after startup.

**Comment by nyrahul** [comment]
@seswarrajan , i thought we already have a way to handle dbclear with corresponding filtering options.

**Comment by seswarrajan** [comment]
Yes @nyrahul We do support dbclear on insight. 
With **insight --req dbclear** currently supports the same.

**Comment by wazir-ahmed** [comment]
@nyrahul @seswarrajan I checked it. The current `karmor` version doesn't have a command `insight --req dbclear`.
